version: '3'
services:
  rabbit:
    build:
      context: ./rabbit
      dockerfile: rabbit.dockerfile
    ports:
      - 15672:15672
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 10s
      timeout: 5s
      retries: 10

  client:
    build:
      context: ./client
      dockerfile: client.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
      - montreal_filter
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./client:/app/client
      - ./client/data:/app/data
      - ./pika_client/pika_client.py:/app/client/pika_client.py

  montreal_filter:
    build:
      context: ./montreal_filter
      dockerfile: montreal_filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
      - montreal_stations
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./montreal_filter:/app/montreal_filter
      - ./pika_client/pika_client.py:/app/montreal_filter/pika_client.py

  rainy_filter:
    build:
      context: ./rainy_filter
      dockerfile: rainy_filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./rainy_filter:/app/rainy_filter
      - ./pika_client/pika_client.py:/app/rainy_filter/pika_client.py

  20162017_filter:
    build:
      context: ./2016&2017_filter
      dockerfile: 2016&2017_filter.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      mode: replicated
      replicas: 3
    volumes:
      - ./2016&2017_filter:/app/2016&2017_filter
      - ./pika_client/pika_client.py:/app/2016&2017_filter/pika_client.py

  20162017_count:
    build:
      context: ./2016&2017_count
      dockerfile: 2016&2017_count.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
      - TOTAL_WORKERS=3
    volumes:
      - ./2016&2017_count:/app/2016&2017_count
      - ./pika_client/pika_client.py:/app/2016&2017_count/pika_client.py

  rainy_durations:
    build:
      context: ./rainy_durations
      dockerfile: rainy_durations.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./rainy_durations:/app/rainy_durations
      - ./pika_client/pika_client.py:/app/rainy_durations/pika_client.py

  montreal_stations:
    build:
      context: ./montreal_stations
      dockerfile: montreal_stations.dockerfile
    restart: on-failure
    depends_on:
      - rabbit
    links:
      - rabbit
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./montreal_stations:/app/montreal_stations
      - ./pika_client/pika_client.py:/app/montreal_stations/pika_client.py
